default_platform(:ios)

platform :ios do

  desc "Push into app distribution firebase"
  lane :beta do
    commit = last_git_commit
    build_number = ENV["BUILD_NUMBER"].to_i

    increment_build_number(
      build_number: build_number
    )

    firebase_app_distribution(
      app: ENV['APP_ID_IOS'],
      groups_file: "./fastlane/groups.txt",
      release_notes: commit[:message],
      firebase_cli_token: ENV['FIREBASE_TOKEN'],
      ipa_path: "#{ENV['FCI_BUILD_OUTPUT_DIR']}/Remote_Care.ipa"
    )
    slack(
      message: "App successfully released!",
      slack_url: ENV['SLACK_URL'],
      payload: {
        "Build Date" => Time.new.to_s,
      },
      default_payloads: [:test_result, :git_author, :last_git_commit, :git_branch],
      attachment_properties: {
        fields: [
          {
            title: "Build number",
            value: "#{build_number}",
          },
          {
            title: "TYPE",
            value: "IOS"
          }
        ]
      }
    )
  end
end
